# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b42d9c99963c6c7d07f50a5797110b3fcc29f2214d4ad3cc1bc1310f9bc9451ccd91719f56d183d4b95cf95125dea7c84c2964d352e5a8e1c62be4dbf8198035

test:
  secret_key_base: 3e01e8154e336d3600f7760accb0b2c723b85e12bcf19dc8a3ea64c2b44758999f94813ce9a4d67d95f6cbb8e121b7e616edc2038a516b25003623def84ee214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
